language: python

jobs:
    include:
      - python: 3.5
      - python: 3.6
      - python: 3.7
        dist: xenial
      - python: 3.8
        dist: xenial

env:
    - REPOSITORY_ORIGIN=smarthome

before_install:
    - sudo apt-get install libudev-dev
    - sudo apt-get install librrd-dev libpython3-dev
install:
    - pip install tox-travis virtualenv
    - pip install sphinx sphinx_rtd_theme recommonmark

script:
    - sh .travis.sh
